### PR TITLE
make the php temp directory configurable

### PR DESCRIPTION
**Pull request by CaptainSifff**
This makes the tmp directory configurable. Useful with nextcloud which wants to write to /tmp ...

### CODE REVIEW

**Review by grisu48 — APPROVED** [review]

**Comment by grisu48** [comment]
Thank you!

**Comment by CaptainSifff** [comment]
Out of curiosity...  have you found time to look at the other roles?

**Comment by grisu48** [comment]
> Out of curiosity... have you found time to look at the other roles?

Not yet but end of January is our Hackweek where I will look at them. I also need to check the molecule tests, so that's gonna be a busy week :slightly_smiling_face: 

And I do appreciate your contributions!

**Comment by CaptainSifff** [comment]
Great to see that there's already some follow-up planned! I have to use the remaining holidays for creating mail-server related roles....
Note to me/others:
There's a good one already available over here: https://github.com/chkpnt/chkpnt-mailserver

**Pull request merged**
