### PR TITLE
Add php-cli

### PR DESCRIPTION
**Pull request by grisu48**
Adds the php-cli package. This is assumed to be needed.

### CODE REVIEW

**Comment by CaptainSifff** [comment]
Good catch! It got installed on my machine. I don't think I did it intentionally, so maybe it was due to some dependency.

**Comment by CaptainSifff** [comment]
So your hackathon is going on now? If you wish, I could visit at least virtually for some time.

**Review by CaptainSifff — APPROVED** [review]
Good catch!

**Comment by grisu48** [comment]
Hackweek starts next week :slightly_smiling_face: But I needed this role for some SLES 15-SP5 testing and encountered this issue then.

No worries, I would anyways like to add `molecule` tests to the project, which should catch those issues before they get merged.

Next week :crossed_fingers:

**Comment by grisu48** [comment]
> So your hackathon is going on now? If you wish, I could visit at least virtually for some time.

No next week. That's totally up to you, you find me on Matrix `phoenix@m1.feldspaten.org` - Feel free to reach out next week if you want to. I also appreciate silent contributions as you've done in the past :slightly_smiling_face: 

Whatever is more comfortable to you!

**Comment by CaptainSifff** [comment]
Hi, I tried reaching you via app.element.io ... is this supposed to work.....?(\me is new on matrix...)

**Comment by grisu48** [comment]
> Hi, I tried reaching you via app.element.io ... is this supposed to work.....?(\me is new on matrix...)

Sorry to hear that, but nothing showed up. If you have issues, don't hesitate to just drop me a email `felix@feldspaten.org` if matrix doesn't work.

**Pull request merged**
