### PR TITLE
Add template for Leap 15.5

### PR DESCRIPTION
**Pull request by grisu48**
Adds variables for the upcoming Leap 15.5 and SLES 15-SP5.

### CODE REVIEW

**Review by CaptainSifff — COMMENTED** [review]
I currently have no 15.5 box available. Has someone reviewed the paths?

**Comment by grisu48** [comment]
> I currently have no 15.5 box available. Has someone reviewed the paths?

I deployed the role to a 15.5 VM using the current Alpha image. Seems to work fine, but I had to disable the `php8-imagick` package, because it's not yet available:

```
./leap15_5.yml 

PLAY [Setup Leap] ******************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
[WARNING]: Platform linux on host leap15_5 is using the discovered Python interpreter at /usr/bin/python3.6, but future installation of another Python interpreter
could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.14/reference_appendices/interpreter_discovery.html for more information.
ok: [leap15_5]

TASK [geekoops-php-fpm : include distribution specific vars] ***********************************************************************************************************
ok: [leap15_5]

TASK [geekoops-php-fpm : Ensure php packages are installed] ************************************************************************************************************
changed: [leap15_5]

TASK [geekoops-php-fpm : Ensure php.ini is configured] *****************************************************************************************************************
changed: [leap15_5]

TASK [geekoops-php-fpm : Ensure php-fpm.conf is configured] ************************************************************************************************************
changed: [leap15_5]

TASK [geekoops-php-fpm : Ensure www.conf is configured] ****************************************************************************************************************
changed: [leap15_5]

TASK [geekoops-php-fpm : Ensure AppArmor knows about our new config file, the socket, and some log files it tries to create] *******************************************
changed: [leap15_5]

TASK [geekoops-php-fpm : create log directory for php-fpm] *************************************************************************************************************
changed: [leap15_5]

TASK [geekoops-php-fpm : Ensure AppArmor is reloaded] ******************************************************************************************************************
changed: [leap15_5]

TASK [geekoops-php-fpm : Ensure php-fpm is enabled] ********************************************************************************************************************
changed: [leap15_5]

RUNNING HANDLER [geekoops-php-fpm : restart php-fpm] *******************************************************************************************************************
changed: [leap15_5]

PLAY RECAP *************************************************************************************************************************************************************
leap15_5                   : ok=11   changed=9    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

The service runs, and the paths look sane, at least as far as I can see:

```
leap15-5:~ # tree /etc/php8
/etc/php8
├── cli
│   └── php.ini
├── conf.d
│   ├── bz2.ini
│   ├── ctype.ini
│   ├── curl.ini
│   ├── dom.ini
│   ├── exif.ini
│   ├── fileinfo.ini
│   ├── gd.ini
│   ├── gettext.ini
│   ├── iconv.ini
│   ├── intl.ini
│   ├── mbstring.ini
│   ├── mysqli.ini
│   ├── _mysqlnd.ini
│   ├── opcache.ini
│   ├── openssl.ini
│   ├── pdo.ini
│   ├── pdo_mysql.ini
│   ├── pdo_sqlite.ini
│   ├── posix.ini
│   ├── sqlite3.ini
│   ├── xmlreader.ini
│   ├── xmlwriter.ini
│   └── zip.ini
└── fpm
    ├── php-fpm.conf
    ├── php-fpm.conf.default
    └── php-fpm.d
        ├── www.conf
        └── www.conf.default

4 directories, 28 files
```

**Comment by CaptainSifff** [comment]
The difficult part was getting apparmor to cooperate... So we would need to check, whether the content of /etc/apparmor.d/php-fpm
or /etc/apparmor.d/local/php-fpm
has changed.

**Comment by grisu48** [comment]
> The difficult part was getting apparmor to cooperate... So we would need to check, whether the content of /etc/apparmor.d/php-fpm or /etc/apparmor.d/local/php-fpm has changed.

Currently trying to get molecule back to work, then we have the CI checks again running.

**Comment by CaptainSifff** [comment]
I wrote you on matrix, me thinks....

**Comment by grisu48** [comment]
> I wrote you on matrix, me thinks....

Hmm, didn't got a message there (I think) :thinking: 

I'm also in the #opensuse-factory, #opensuse-chat, #opensuse-bar channels

**Comment by grisu48** [comment]
> The difficult part was getting apparmor to cooperate... So we would need to check, whether the content of /etc/apparmor.d/php-fpm or /etc/apparmor.d/local/php-fpm has changed.

Until Leap 15.5 is released, does it make sense to invest time in this? I see this as a template to fix it when time comes to actually enable it. WDYT?

**Comment by CaptainSifff** [comment]
So we think of 15.5 support as just sth. something where we already have the templates? I thought, since you are involved in SuSE you might have some insight, whether apparmor is tightening up php-fpm further....

**Comment by grisu48** [comment]
> So we think of 15.5 support as just sth. something where we already have the templates? I thought, since you are involved in SuSE you might have some insight, whether apparmor is tightening up php-fpm further....

About apparmor: No idea, someone different is working on this. Also it looks like AppArmor is slowly being replaced by SELinux, so I would not put too much effort in this (take this with a grain of salt though).

I just used this role for Beta testing, where it was pretty useful, that's why I included the template here. Nothing else :slightly_smiling_face:

**Comment by grisu48** [comment]
I'm merging this for now, since there were no obvious blockers. Feel free to open any issues, also in regard of AppArmor if applicable.

**Pull request merged**
